### PR TITLE
CLR support

### PR DESCRIPTION
**Pull request by nasser**
These changes add ClojureCLR support to the library. The port was mostly straightforward with minor differences with respect to streams on the CLR vs the JVM and byte signedness. All tests are passing.

### CODE REVIEW

**Comment by bbatsov** [comment]
Nice! 

The build seems to be failing, but the changes look good to me overall. I'd be nice if we incorporated CLR in the build matrix as well - I think I heard that now it works on Linux as well. 

Out of curiosity - what's your use-case? Is this some step towards working to port nREPL itself to support CLR?

**Comment by nasser** [comment]
This is a step towards getting nREPL running in [Arcadia](https://github.com/arcadia-unity/arcadia) in particular and on ClojureCLR in general. The [current prototype](https://github.com/arcadia-unity/Arcadia/blob/new-repl/Editor/NRepl.cs) is very limited (basically just `eval`) and implemented in C#, but as we expand the port we will likely use the Clojure implementation.

**Comment by bbatsov** [comment]
@nasser Nice! 

Let me know when you get the build to pass and I'll merge the PR.

**Comment by nasser** [comment]
will do :v:

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  pr inactive since 200 days. Please update the PR or close it

**Comment by bbatsov** [comment]
@nasser recently told me this PR is no longer relevant as they've added a different bencode library.

**Pull request closed without merging**
