### PR TITLE
Port bencode re-implementation from nREPL 1.2.0

### PR DESCRIPTION
**Pull request by alexander-yakushev**

### CODE REVIEW

**Comment by bbatsov** [comment]
Seems that something's wrong with the CI: 

```
Writing SSH key for checkout to "/root/.ssh/id_rsa"
Writing SSH public key for checkout to "/root/.ssh/id_rsa.pub"
Cloning git repository
Cloning into '.'...
Warning: Permanently added the ECDSA host key for IP address '140.82.113.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error running git clone "git@github.com:nrepl/bencode.git": exit status 128
```

Likely the keys will have to be regenerated or something. I'll see if I can fix this later.

**Comment by bbatsov** [comment]
I've regenerated the SSH key for CircleCI and the CI is working now.

**Comment by alexander-yakushev** [comment]
Passes now.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
